In [12]:
import torch
from torch.utils import data
from torch.utils.data import DataLoader
from torch import nn
import torch.nn.functional as F

import random
from collections import Counter, defaultdict
import pandas as pd
import numpy as np
import scipy
from tqdm import trange
from tqdm import tqdm
from datetime import datetime
import sys
import os
import time
from sklearn.metrics import roc_auc_score, f1_score
from IPython.display import clear_output

from transformers import BertModel, BertConfig, PreTrainedTokenizer, BasicTokenizer, BertForTokenClassification, utils

import sklearn
from sklearn.metrics import accuracy_score

from Bio import SeqIO
from io import StringIO, BytesIO

import gc

import warnings
warnings.filterwarnings("ignore")

In [ ]:
from dna_tokenizer import DNATokenizer, seq2kmer

In [ ]:
from tabulate import tabulate
def to_fwf(df, fname):
    content = tabulate(df.values.tolist(), tablefmt="plain")
    open(fname, "w").write(content)

pd.DataFrame.to_fwf = to_fwf

In [ ]:
def split_seq(seq, length = 512, pad = 16):
    res = []
    n = len(seq)
    for st in range(0, n, length - pad):
        if st > 0 and st + pad >= n:
            break
        end = min(st+length, n)
        res.append(seq[st:end])
    return res

In [ ]:
def stitch_np_seq(np_seqs, pad=16):
    # Calculate total length first to pre-allocate array
    total_length = sum(seq.shape[-1] for seq in np_seqs) - pad * (len(np_seqs) - 1)
    
    # Pre-allocate result array
    res = np.empty(total_length, dtype=np_seqs[0].dtype)
    
    # Track current position
    pos = 0
    
    for i, seq in enumerate(np_seqs):
        seq_len = seq.shape[-1]
        if i > 0:
            # Overlap by removing 'pad' elements from previous segment
            pos -= pad
        # Copy current sequence into the result
        #print(pos,pos+seq_len)
        res[pos:pos+seq_len] = seq[0,:]
        pos += seq_len
    
    return res

In [ ]:
class PredDataset(data.Dataset):
    def __init__(self, sequence, tokenizer):
        self.pieces = split_seq(seq2kmer(sequence.upper(),6).split(' '), length = 512, pad = 16)
        self.tokenizer = tokenizer
        
    def __len__(self):
        return len(self.pieces)
    
    def __getitem__(self, index):
        sequence = self.pieces[index]
        encoded_k_mers = self.tokenizer.encode_plus(sequence, add_special_tokens=False, max_length=512)["input_ids"]
        return torch.LongTensor(encoded_k_mers)

In [ ]:
tokenizer = DNATokenizer.from_pretrained('6-new-12w-0/')

In [2]:
import pickle
import gc

pickle_dir = 'predictions'

def get_pickle_filename(name):
    """Determine the appropriate pickle filename based on the name pattern"""
    if name.startswith('NW_'):
        return os.path.join(pickle_dir, 'NW__all.pickle')
    else:
        return os.path.join(pickle_dir, f'{name}.pickle')
    
def name_already_processed(name):
    """Check if a name has already been processed by looking for its pickle file"""    
    if os.path.exists(get_pickle_filename(name)):
        if name.startswith('NW_'):
            try:
                with open(pickle_file, 'rb') as f:
                    existing_data = pickle.load(f)
                    return name in existing_data
            except:
                return False
        return True
    return False

In [5]:
import numpy as np
import scipy.ndimage

def extract_segments_1d(arr, name, threshold, min_len,
                        chr_names, starts, ends, scores):
    mask = arr > threshold
    labeled, n = scipy.ndimage.label(mask)

    if n == 0:
        return

    # For 1D labels, each object is returned as a tuple like (slice(start, stop),)
    objects = scipy.ndimage.find_objects(labeled)

    for slc_tuple in objects:
        if slc_tuple is None:
            continue
        slc = slc_tuple[0]
        start, end = slc.start, slc.stop

        if end - start > min_len:
            seg_score = float(arr[start:end].mean())
            chr_names.append(name)
            starts.append(start)
            ends.append(end)
            scores.append(seg_score)

In [6]:
from tqdm import trange
model_confidence_threshold = 0.25
min_len = 4

chr_names, starts, ends, scores = [], [], [], []

for fname in os.listdir('predictions/'):
    print(fname)
    with open('predictions/' + fname,'rb') as f:
        preds = pickle.load(f)
        
    if fname.startswith('NW_'):
        for k, arr in preds.items():
            print(k, arr.shape)
            extract_segments_1d(
            arr=arr,
            name=k,
            threshold=model_confidence_threshold,
            min_len=min_len,
            chr_names=chr_names,
            starts=starts,
            ends=ends,
            scores=scores,
        )
    else:
        print(preds.shape)
        extract_segments_1d(
        arr=preds,
        name=fname.replace('.pickle', ''),
        threshold=model_confidence_threshold,
        min_len=min_len,
        chr_names=chr_names,
        starts=starts,
        ends=ends,
        scores=scores,
    )

NC_068981.1.pickle
(199874324,)
NC_068982.1.pickle
(192492725,)
NC_068983.1.pickle
(168056172,)
NC_068984.1.pickle
(147805811,)
NC_068985.1.pickle
(127476054,)
NC_068986.1.pickle
(117080274,)
NC_068987.1.pickle
(110520654,)
NC_068988.1.pickle
(97793168,)
NC_068989.1.pickle
(96881191,)
NC_068990.1.pickle
(94598369,)
NC_068991.1.pickle
(80868366,)
NC_068992.1.pickle
(68459955,)
NC_068993.1.pickle
(65066832,)
NC_068994.1.pickle
(60576129,)
NC_068995.1.pickle
(58155570,)
NC_068996.1.pickle
(57524426,)
NC_068997.1.pickle
(57421545,)
NC_068998.1.pickle
(55557499,)
NC_068999.1.pickle
(55137724,)
NC_069000.1.pickle
(47890966,)
NC_069001.1.pickle
(40062745,)
NC_069002.1.pickle
(37717994,)
NC_069003.1.pickle
(37682606,)
NC_069004.1.pickle
(36166158,)
NC_069005.1.pickle
(35489831,)
NC_069006.1.pickle
(26644802,)
NC_069007.1.pickle
(22553644,)
NC_069008.1.pickle
(18637140,)
NC_069009.1.pickle
(11991808,)
NC_069010.1.pickle
(10083076,)
NC_029723.1.pickle
(15728,)
NW__all.pickle
NW_026294888.1 (344,)
NW_026294889.1 (825,)
NW_026294890.1 (381,)
NW_026294891.1 (387,)
NW_026294892.1 (318,)
NW_026294893.1 (469,)
NW_026294894.1 (338,)
NW_026294895.1 (491,)
NW_026294896.1 (420,)
NW_026294897.1 (354,)
NW_026294898.1 (225,)
NW_026294899.1 (235,)
NW_026294900.1 (312,)
NW_026294901.1 (365,)
NW_026294902.1 (359,)
NW_026294903.1 (422,)
NW_026294904.1 (460,)
NW_026294905.1 (2874,)
NW_026294906.1 (485,)
NW_026294907.1 (633,)
NW_026294908.1 (671,)
NW_026294909.1 (2554,)
NW_026294910.1 (209,)
NW_026294911.1 (214,)
NW_026294912.1 (235,)
NW_026294913.1 (813,)
NW_026294914.1 (488,)
NW_026294915.1 (202,)
NW_026294916.1 (244,)
NW_026294917.1 (519,)
NW_026294918.1 (446,)
NW_026294919.1 (207,)
NW_026294920.1 (393,)
NW_026294921.1 (401,)
NW_026294922.1 (220,)
NW_026294923.1 (453,)
NW_026294924.1 (344,)
NW_026294925.1 (215,)
NW_026294926.1 (451,)
NW_026294927.1 (1736,)
NW_026294928.1 (245,)
NW_026294929.1 (395,)
NW_026294930.1 (339,)
NW_026294931.1 (249,)
NW_026294932.1 (231,)
NW_026294933.1 (211,)
NW_026294934.1 (331,)
NW_026294935.1 (198,)
NW_026294936.1 (483,)
NW_026294937.1 (547,)
NW_026294938.1 (412,)
NW_026294939.1 (494,)
NW_026294940.1 (257,)
NW_026294941.1 (271,)
NW_026294942.1 (254,)
NW_026294943.1 (634,)
NW_026294944.1 (315,)
NW_026294945.1 (390,)
NW_026294946.1 (520,)
NW_026294947.1 (545,)
NW_026294948.1 (297,)
NW_026294949.1 (630,)
NW_026294950.1 (535,)
NW_026294951.1 (495,)
NW_026294952.1 (540,)
NW_026294953.1 (198,)
NW_026294954.1 (244,)
NW_026294955.1 (223,)
NW_026294956.1 (679,)
NW_026294957.1 (267,)
NW_026294958.1 (397,)
NW_026294959.1 (351,)
NW_026294960.1 (355,)
NW_026294961.1 (344,)
NW_026294962.1 (274,)
NW_026294963.1 (356,)
NW_026294964.1 (360,)
NW_026294965.1 (211,)
NW_026294966.1 (298,)
NW_026294967.1 (423,)
NW_026294968.1 (238,)
NW_026294969.1 (362,)
NW_026294970.1 (446,)
NW_026294971.1 (372,)
NW_026294972.1 (258,)
NW_026294973.1 (272,)
NW_026294974.1 (223,)
NW_026294975.1 (364,)
NW_026294976.1 (251,)
NW_026294977.1 (647,)
NW_026294978.1 (420,)
NW_026294979.1 (364,)
NW_026294980.1 (740,)
NW_026294981.1 (199,)
NW_026294982.1 (361,)
NW_026294983.1 (254,)
NW_026294984.1 (507,)
NW_026294985.1 (213,)
NW_026294986.1 (533,)
NW_026294987.1 (333,)
NW_026294988.1 (276,)
NW_026294989.1 (205,)
NW_026294990.1 (197,)
NW_026294991.1 (2002,)
NW_026294992.1 (397,)
NW_026294993.1 (775,)
NW_026294994.1 (370,)
NW_026294995.1 (627,)
NW_026294996.1 (224,)
NW_026294997.1 (470,)
NW_026294998.1 (332,)
NW_026294999.1 (314,)
NW_026295000.1 (340,)
NW_026295001.1 (316,)
NW_026295002.1 (690,)
NW_026295003.1 (265,)
NW_026295004.1 (428,)
NW_026295005.1 (358,)
NW_026295006.1 (435,)
NW_026295007.1 (315,)
NW_026295008.1 (365,)
NW_026295009.1 (540,)
NW_026295010.1 (298,)
NW_026295011.1 (470,)
NW_026295012.1 (410,)
NW_026295013.1 (197,)
NW_026295014.1 (509,)
NW_026295015.1 (352,)
NW_026295016.1 (2151,)
NW_026295017.1 (263,)
NW_026295018.1 (207,)
NW_026295019.1 (2030,)
NW_026295020.1 (507,)
NW_026295021.1 (478,)
NW_026295022.1 (428,)
NW_026295023.1 (469,)
NW_026295024.1 (468,)
NW_026295025.1 (463,)
NW_026295026.1 (366,)
NW_026295027.1 (458,)
NW_026295028.1 (304,)
NW_026295029.1 (210,)
NW_026295030.1 (1318,)
NW_026295031.1 (198,)
NW_026295032.1 (1952,)
NW_026295033.1 (1250,)
NW_026295034.1 (540,)
NW_026295035.1 (288,)
NW_026295036.1 (513,)
NW_026295037.1 (712,)
NW_026295038.1 (297,)
NW_026295039.1 (229,)
NW_026295040.1 (447,)
NW_026295041.1 (225,)
NW_026295042.1 (206,)
NW_026295043.1 (253,)
NW_026295044.1 (363,)
NW_026295045.1 (553,)
NW_026295046.1 (319,)
NW_026295047.1 (647,)
NW_026295048.1 (548,)
NW_026295049.1 (2365,)
NW_026295050.1 (426,)
NW_026295051.1 (430,)
NW_026295052.1 (266,)
NW_026295053.1 (219,)
NW_026295054.1 (610,)
NW_026295055.1 (445,)
NW_026295056.1 (334,)
NW_026295057.1 (279,)
NW_026295058.1 (218,)
NW_026295059.1 (317,)
NW_026295060.1 (12136,)
NW_026295061.1 (308,)
NW_026295062.1 (348,)
NW_026295063.1 (337,)
NW_026295064.1 (203,)
NW_026295065.1 (302,)
NW_026295066.1 (635,)
NW_026295067.1 (382,)
NW_026295068.1 (287,)
NW_026295069.1 (575,)
NW_026295070.1 (510,)
NW_026295071.1 (212,)
NW_026295072.1 (475,)
NW_026295073.1 (399,)
NW_026295074.1 (355,)
NW_026295075.1 (363,)
NW_026295076.1 (235,)
NW_026295077.1 (738,)
NW_026295078.1 (245,)
NW_026295079.1 (2031,)
NW_026295080.1 (271,)
NW_026295081.1 (348,)
NW_026295082.1 (333,)
NW_026295083.1 (564,)
NW_026295084.1 (350,)
NW_026295085.1 (216,)
NW_026295086.1 (202,)
NW_026295087.1 (227,)
NW_026295088.1 (238,)
NW_026295089.1 (226,)
NW_026295090.1 (234,)
NW_026295091.1 (392,)
NW_026295092.1 (666,)
NW_026295093.1 (289,)
NW_026295094.1 (229,)
NW_026295095.1 (198,)
NW_026295096.1 (390,)
NW_026295097.1 (239,)
NW_026295098.1 (238,)
NW_026295099.1 (618,)
NW_026295100.1 (253,)
NW_026295101.1 (227,)
NW_026295102.1 (230,)
NW_026295103.1 (283,)
NW_026295104.1 (212,)
NW_026295105.1 (447,)
NW_026295106.1 (451,)
NW_026295107.1 (409,)
NW_026295108.1 (437,)
NW_026295109.1 (314,)
NW_026295110.1 (288,)
NW_026295111.1 (223,)
NW_026295112.1 (503,)
NW_026295113.1 (266,)
NW_026295114.1 (377,)
NW_026295115.1 (952,)
NW_026295116.1 (261,)
NW_026295117.1 (264,)
NW_026295118.1 (543,)
NW_026295119.1 (751,)
NW_026295120.1 (739,)
NW_026295121.1 (238,)
NW_026295122.1 (217,)
NW_026295123.1 (623,)
NW_026295124.1 (317,)
NW_026295125.1 (495,)
NW_026295126.1 (235,)
NW_026295127.1 (509,)
NW_026295128.1 (196,)
NW_026295129.1 (253,)
NW_026295130.1 (463,)
NW_026295131.1 (414,)
NW_026295132.1 (638,)
NW_026295133.1 (294,)
NW_026295134.1 (222,)
NW_026295135.1 (445,)
NW_026295136.1 (703,)
NW_026295137.1 (447,)
NW_026295138.1 (441,)
NW_026295139.1 (247,)
NW_026295140.1 (279,)
NW_026295141.1 (547,)
NW_026295142.1 (1338,)
NW_026295143.1 (671,)
NW_026295144.1 (2101,)
NW_026295145.1 (470,)
NW_026295146.1 (527,)
NW_026295147.1 (490,)
NW_026295148.1 (672,)
NW_026295149.1 (323,)
NW_026295150.1 (1077,)
NW_026295151.1 (221,)
NW_026295152.1 (2869,)
NW_026295153.1 (239,)
NW_026295154.1 (226,)
NW_026295155.1 (437,)
NW_026295156.1 (246,)
NW_026295157.1 (352,)
NW_026295158.1 (506,)
NW_026295159.1 (566,)
NW_026295160.1 (307,)
NW_026295161.1 (357,)
NW_026295162.1 (203,)
NW_026295163.1 (242,)
NW_026295164.1 (215,)
NW_026295165.1 (211,)
NW_026295166.1 (219,)
NW_026295167.1 (231,)
NW_026295168.1 (794,)
NW_026295169.1 (198,)
NW_026295170.1 (520,)
NW_026295171.1 (374,)
NW_026295172.1 (483,)
NW_026295173.1 (18630,)
NW_026295174.1 (417,)
NW_026295175.1 (421,)
NW_026295176.1 (236,)
NW_026295177.1 (396,)
NW_026295178.1 (542,)
NW_026295179.1 (278,)
NW_026295180.1 (357,)
NW_026295181.1 (483,)
NW_026295182.1 (227,)
NW_026295183.1 (394,)
NW_026295184.1 (330,)
NW_026295185.1 (456,)
NW_026295186.1 (290,)
NW_026295187.1 (201,)
NW_026295188.1 (582,)
NW_026295189.1 (319,)
NW_026295190.1 (1899,)
NW_026295191.1 (266,)
NW_026295192.1 (205,)
NW_026295193.1 (353,)
NW_026295194.1 (319,)
NW_026295195.1 (225,)
NW_026295196.1 (1152,)
NW_026295197.1 (1029,)
NW_026295198.1 (964,)
NW_026295199.1 (459,)
NW_026295200.1 (493,)
NW_026295201.1 (278,)
NW_026295202.1 (322,)
NW_026295203.1 (222,)
NW_026295204.1 (343,)
NW_026295205.1 (343,)
NW_026295206.1 (231,)
NW_026295207.1 (206,)
NW_026295208.1 (629,)
NW_026295209.1 (2085,)
NW_026295210.1 (407,)
NW_026295211.1 (394,)
NW_026295212.1 (219,)
NW_026295213.1 (214,)
NW_026295214.1 (979,)
NW_026295215.1 (299,)
NW_026295216.1 (491,)
NW_026295217.1 (623,)
NW_026295218.1 (14427,)
NW_026295219.1 (487,)
NW_026295220.1 (322,)
NW_026295221.1 (198,)
NW_026295222.1 (534,)
NW_026295223.1 (283,)
NW_026295224.1 (290,)
NW_026295225.1 (445,)
NW_026295226.1 (574,)
NW_026295227.1 (202,)
NW_026295228.1 (467,)
NW_026295229.1 (370,)
NW_026295230.1 (529,)
NW_026295231.1 (359,)
NW_026295232.1 (391,)
NW_026295233.1 (585,)
NW_026295234.1 (350,)
NW_026295235.1 (243,)
NW_026295236.1 (220,)
NW_026295237.1 (963,)
NW_026295238.1 (370,)
NW_026295239.1 (508,)
NW_026295240.1 (266,)
NW_026295241.1 (383,)
NW_026295242.1 (447,)
NW_026295243.1 (518,)
NW_026295244.1 (314,)
NW_026295245.1 (275,)
NW_026295246.1 (322,)
NW_026295247.1 (211,)
NW_026295248.1 (616,)
NW_026295249.1 (350,)
NW_026295250.1 (239,)
NW_026295251.1 (222,)
NW_026295252.1 (308,)
NW_026295253.1 (253,)
NW_026295254.1 (622,)
NW_026295255.1 (268,)
NW_026295256.1 (378,)
NW_026295257.1 (226,)
NW_026295258.1 (660,)
NW_026295259.1 (1817,)
NW_026295260.1 (570,)
NW_026295261.1 (4845,)
NW_026295262.1 (2742,)
NW_026295263.1 (573,)
NW_026295264.1 (537,)
NW_026295265.1 (450,)
NW_026295266.1 (853,)
NW_026295267.1 (216,)
NW_026295268.1 (3440,)
NW_026295269.1 (1588,)
NW_026295270.1 (228,)
NW_026295271.1 (205,)
NW_026295272.1 (357,)
NW_026295273.1 (528,)
NW_026295274.1 (255,)
NW_026295275.1 (229,)
NW_026295276.1 (398,)
NW_026295277.1 (525,)
NW_026295278.1 (368,)
NW_026295279.1 (527,)
NW_026295280.1 (342,)
NW_026295281.1 (323,)
NW_026295282.1 (490,)
NW_026295283.1 (344,)
NW_026295284.1 (493,)
NW_026295285.1 (452,)
NW_026295286.1 (591,)
NW_026295287.1 (471,)
NW_026295288.1 (273,)
NW_026295289.1 (250,)
NW_026295290.1 (288,)
NW_026295291.1 (291,)
NW_026295292.1 (285,)
NW_026295293.1 (2161,)
NW_026295294.1 (619,)
NW_026295295.1 (388,)
NW_026295296.1 (292,)
NW_026295297.1 (621,)
NW_026295298.1 (416,)
NW_026295299.1 (331,)
NW_026295300.1 (298,)
NW_026295301.1 (1356,)
NW_026295302.1 (349,)
NW_026295303.1 (200,)
NW_026295304.1 (1896,)
NW_026295305.1 (297,)
NW_026295306.1 (555,)
NW_026295307.1 (213,)
NW_026295308.1 (221,)
NW_026295309.1 (438,)
NW_026295310.1 (614,)
NW_026295311.1 (740,)
NW_026295312.1 (780,)
NW_026295313.1 (209,)
NW_026295314.1 (478,)
NW_026295315.1 (231,)
NW_026295316.1 (275,)
NW_026295317.1 (215,)
NW_026295318.1 (494,)
NW_026295319.1 (393,)
NW_026295320.1 (465,)
NW_026295321.1 (265,)
NW_026295322.1 (649,)
NW_026295323.1 (389,)
NW_026295324.1 (266,)
NW_026295325.1 (289,)
NW_026295326.1 (4732,)
NW_026295327.1 (342,)
NW_026295328.1 (198,)
NW_026295329.1 (357,)
NW_026295330.1 (500,)
NW_026295331.1 (422,)
NW_026295332.1 (20059,)
NW_026295333.1 (369,)
NW_026295334.1 (1095,)
NW_026295335.1 (256,)
NW_026295336.1 (4750,)
NW_026295337.1 (517,)
NW_026295338.1 (474,)
NW_026295339.1 (198,)
NW_026295340.1 (681,)
NW_026295341.1 (271,)
NW_026295342.1 (372,)
NW_026295343.1 (202,)
NW_026295344.1 (570,)
NW_026295345.1 (1989,)
NW_026295346.1 (658,)
NW_026295347.1 (223,)
NW_026295348.1 (425,)
NW_026295349.1 (429,)
NW_026295350.1 (13614,)
NW_026295351.1 (223,)
NW_026295352.1 (676,)
NW_026295353.1 (374,)
NW_026295354.1 (522,)
NW_026295355.1 (363,)
NW_026295356.1 (649,)
NW_026295357.1 (811,)
NW_026295358.1 (637,)
NW_026295359.1 (615,)
NW_026295360.1 (546,)
NW_026295361.1 (320,)
NW_026295362.1 (541,)
NW_026295363.1 (424,)
NW_026295364.1 (714,)
NW_026295365.1 (549,)
NW_026295366.1 (322,)
NW_026295367.1 (597,)
NW_026295368.1 (429,)
NW_026295369.1 (530,)
NW_026295370.1 (420,)
NW_026295371.1 (378,)
NW_026295372.1 (1140,)
NW_026295373.1 (696,)
NW_026295374.1 (195,)
NW_026295375.1 (362,)
NW_026295376.1 (252,)
NW_026295377.1 (1013,)
NW_026295378.1 (439,)
NW_026295379.1 (279,)
NW_026295380.1 (568,)
NW_026295381.1 (239,)
NW_026295382.1 (464,)
NW_026295383.1 (344,)
NW_026295384.1 (260,)
NW_026295385.1 (3072,)
NW_026295386.1 (255,)
NW_026295387.1 (428,)
NW_026295388.1 (252,)
NW_026295389.1 (1657,)
NW_026295390.1 (354,)
NW_026295391.1 (374,)
NW_026295392.1 (272,)
NW_026295393.1 (348,)
NW_026295394.1 (298,)
NW_026295395.1 (267,)
NW_026295396.1 (602,)
NW_026295397.1 (204,)
NW_026295398.1 (1102,)
NW_026295399.1 (326,)
NW_026295400.1 (341,)
NW_026295401.1 (254,)
NW_026295402.1 (218,)
NW_026295403.1 (258,)
NW_026295404.1 (522,)
NW_026295405.1 (233,)
NW_026295406.1 (547,)
NW_026295407.1 (512,)
NW_026295408.1 (1931,)
NW_026295409.1 (576,)
NW_026295410.1 (1457,)
NW_026295411.1 (379,)
NW_026295412.1 (324,)
NW_026295413.1 (227,)
NW_026295414.1 (577,)
NW_026295415.1 (309,)
NW_026295416.1 (228,)
NW_026295417.1 (354,)
NW_026295418.1 (257,)
NW_026295419.1 (259,)
NW_026295420.1 (342,)
NW_026295421.1 (500,)
NW_026295422.1 (617,)
NW_026295423.1 (535,)
NW_026295424.1 (515,)
NW_026295425.1 (10376,)
NW_026295426.1 (375,)
NW_026295427.1 (1183,)
NW_026295428.1 (468,)
NW_026295429.1 (2024,)
NW_026295430.1 (210,)
NW_026295431.1 (728,)
NW_026295432.1 (365,)
NW_026295433.1 (476,)
NW_026295434.1 (351,)
NW_026295435.1 (2291,)
NW_026295436.1 (4111,)
NW_026295437.1 (1771,)
NW_026295438.1 (1633,)
NW_026295439.1 (196,)
NW_026295440.1 (309,)
NW_026295441.1 (676,)
NW_026295442.1 (438,)
NW_026295443.1 (254,)
NW_026295444.1 (391,)
NW_026295445.1 (525,)
NW_026295446.1 (405,)
NW_026295447.1 (2112,)
NW_026295448.1 (373,)
NW_026295449.1 (583,)
NW_026295450.1 (362,)
NW_026295451.1 (399,)
NW_026295452.1 (316,)
NW_026295453.1 (233,)
NW_026295454.1 (236,)
NW_026295455.1 (244,)
NW_026295456.1 (270,)
NW_026295457.1 (230,)
NW_026295458.1 (243,)
NW_026295459.1 (524,)
NW_026295460.1 (227,)
NW_026295461.1 (203,)
NW_026295462.1 (386,)
NW_026295463.1 (633,)
NW_026295464.1 (204,)
NW_026295465.1 (223,)
NW_026295466.1 (206,)
NW_026295467.1 (234,)
NW_026295468.1 (2012,)
NW_026295469.1 (575,)
NW_026295470.1 (291,)
NW_026295471.1 (298,)
NW_026295472.1 (465,)
NW_026295473.1 (536,)
NW_026295474.1 (247,)
NW_026295475.1 (219,)
NW_026295476.1 (230,)
NW_026295477.1 (397,)
NW_026295478.1 (263,)
NW_026295479.1 (273,)
NW_026295480.1 (1940,)
NW_026295481.1 (199,)
NW_026295482.1 (273,)
NW_026295483.1 (1900,)
NW_026295484.1 (359,)
NW_026295485.1 (304,)
NW_026295486.1 (216,)
NW_026295487.1 (432,)
NW_026295488.1 (365,)
NW_026295489.1 (378,)
NW_026295490.1 (694,)
NW_026295491.1 (339,)
NW_026295492.1 (338,)
NW_026295493.1 (207,)
NW_026295494.1 (204,)
NW_026295495.1 (525,)
NW_026295496.1 (239,)
NW_026295497.1 (315,)
NW_026295498.1 (416,)
NW_026295499.1 (320,)
NW_026295500.1 (258,)
NW_026295501.1 (351,)
NW_026295502.1 (237,)
NW_026295503.1 (480,)
NW_026295504.1 (362,)
NW_026295505.1 (686,)
NW_026295506.1 (556,)
NW_026295507.1 (208,)
NW_026295508.1 (397,)
NW_026295509.1 (593,)
NW_026295510.1 (241,)
NW_026295511.1 (580,)
NW_026295512.1 (4140,)
NW_026295513.1 (223,)
NW_026295514.1 (453,)
NW_026295515.1 (549,)
NW_026295516.1 (237,)
NW_026295517.1 (367,)
NW_026295518.1 (415,)
NW_026295519.1 (294,)
NW_026295520.1 (29748,)
NW_026295521.1 (560,)
NW_026295522.1 (214,)
NW_026295523.1 (301,)
NW_026295524.1 (487,)
NW_026295525.1 (492,)
NW_026295526.1 (217,)
NW_026295527.1 (8299,)
NW_026295528.1 (1176,)
NW_026295529.1 (3603,)
NW_026295530.1 (230,)
NW_026295531.1 (293,)
NW_026295532.1 (465,)
NW_026295533.1 (535,)
NW_026295534.1 (406,)
NW_026295535.1 (204,)
NW_026295536.1 (601,)
NW_026295537.1 (334,)
NW_026295538.1 (756,)
NW_026295539.1 (487,)
NW_026295540.1 (359,)
NW_026295541.1 (213,)
NW_026295542.1 (489,)
NW_026295543.1 (433,)
NW_026295544.1 (313,)
NW_026295545.1 (355,)
NW_026295546.1 (255,)
NW_026295547.1 (355,)
NW_026295548.1 (211,)
NW_026295549.1 (387,)
NW_026295550.1 (4975,)
NW_026295551.1 (471,)
NW_026295552.1 (268,)
NW_026295553.1 (536,)
NW_026295554.1 (393,)
NW_026295555.1 (570,)
NW_026295556.1 (643,)
NW_026295557.1 (8710,)
NW_026295558.1 (577,)
NW_026295559.1 (558,)
NW_026295560.1 (199,)
NW_026295561.1 (1532,)
NW_026295562.1 (433,)
NW_026295563.1 (330,)
NW_026295564.1 (207,)
NW_026295565.1 (362,)
NW_026295566.1 (254,)
NW_026295567.1 (5947,)
NW_026295568.1 (416,)
NW_026295569.1 (242,)
NW_026295570.1 (471,)
NW_026295571.1 (312,)
NW_026295572.1 (573,)
NW_026295573.1 (446,)
NW_026295574.1 (462,)
NW_026295575.1 (538,)
NW_026295576.1 (5129,)
NW_026295577.1 (290,)
NW_026295578.1 (438,)
NW_026295579.1 (478,)
NW_026295580.1 (210,)
NW_026295581.1 (216,)
NW_026295582.1 (236,)
NW_026295583.1 (316,)
NW_026295584.1 (446,)
NW_026295585.1 (602,)
NW_026295586.1 (325,)
NW_026295587.1 (361,)
NW_026295588.1 (589,)
NW_026295589.1 (316,)
NW_026295590.1 (891,)
NW_026295591.1 (231,)
NW_026295592.1 (441,)
NW_026295593.1 (521,)
NW_026295594.1 (759,)
NW_026295595.1 (531,)
NW_026295596.1 (474,)
NW_026295597.1 (213,)
NW_026295598.1 (522,)
NW_026295599.1 (593,)
NW_026295600.1 (552,)
NW_026295601.1 (457,)
NW_026295602.1 (626,)
NW_026295603.1 (737,)
NW_026295604.1 (231,)
NW_026295605.1 (414,)
NW_026295606.1 (241,)
NW_026295607.1 (242,)
NW_026295608.1 (524,)
NW_026295609.1 (199,)
NW_026295610.1 (208,)
NW_026295611.1 (295,)
NW_026295612.1 (473,)
NW_026295613.1 (284,)
NW_026295614.1 (427,)
NW_026295615.1 (287,)
NW_026295616.1 (308,)
NW_026295617.1 (422,)
NW_026295618.1 (211,)
NW_026295619.1 (266,)
NW_026295620.1 (224,)
NW_026295621.1 (604,)
NW_026295622.1 (490,)
NW_026295623.1 (312,)
NW_026295624.1 (4145,)
NW_026295625.1 (265,)
NW_026295626.1 (387,)
NW_026295627.1 (1886,)
NW_026295628.1 (502,)
NW_026295629.1 (457,)
NW_026295630.1 (218,)
NW_026295631.1 (232,)
NW_026295632.1 (1578,)
NW_026295633.1 (1965,)
NW_026295634.1 (4956,)
NW_026295635.1 (395,)
NW_026295636.1 (273,)
NW_026295637.1 (240,)
NW_026295638.1 (297,)
NW_026295639.1 (218,)
NW_026295640.1 (197,)
NW_026295641.1 (245,)
NW_026295642.1 (344,)
NW_026295643.1 (316,)
NW_026295644.1 (309,)
NW_026295645.1 (276,)
NW_026295646.1 (658,)
NW_026295647.1 (853,)
NW_026295648.1 (228,)
NW_026295649.1 (333,)
NW_026295650.1 (369,)
NW_026295651.1 (207,)
NW_026295652.1 (281,)
NW_026295653.1 (345,)
NW_026295654.1 (334,)
NW_026295655.1 (692,)
NW_026295656.1 (405,)
NW_026295657.1 (385,)
NW_026295658.1 (270,)
NW_026295659.1 (206,)
NW_026295660.1 (236,)
NW_026295661.1 (353,)
NW_026295662.1 (504,)
NW_026295663.1 (287,)
NW_026295664.1 (207,)
NW_026295665.1 (408,)
NW_026295666.1 (509,)
NW_026295667.1 (289,)
NW_026295668.1 (553,)
NW_026295669.1 (758,)
NW_026295670.1 (1451,)
NW_026295671.1 (261,)
NW_026295672.1 (604,)
NW_026295673.1 (1100,)
NW_026295674.1 (220,)
NW_026295675.1 (653,)
NW_026295676.1 (450,)
NW_026295677.1 (373,)
NW_026295678.1 (325,)
NW_026295679.1 (205,)
NW_026295680.1 (234,)
NW_026295681.1 (623,)
NW_026295682.1 (242,)
NW_026295683.1 (366,)
NW_026295684.1 (577,)
NW_026295685.1 (268,)
NW_026295686.1 (242,)
NW_026295687.1 (238,)
NW_026295688.1 (268,)
NW_026295689.1 (200,)
NW_026295690.1 (2061,)
NW_026295691.1 (3820,)
NW_026295692.1 (247,)
NW_026295693.1 (558,)
NW_026295694.1 (912,)
NW_026295695.1 (562,)
NW_026295696.1 (428,)
NW_026295697.1 (223,)
NW_026295698.1 (349,)
NW_026295699.1 (577,)
NW_026295700.1 (264,)
NW_026295701.1 (248,)
NW_026295702.1 (210,)
NW_026295703.1 (246,)
NW_026295704.1 (315,)
NW_026295705.1 (214,)
NW_026295706.1 (385,)
NW_026295707.1 (347,)
NW_026295708.1 (329,)
NW_026295709.1 (18688,)
NW_026295710.1 (203,)
NW_026295711.1 (369,)
NW_026295712.1 (249,)
NW_026295713.1 (252,)
NW_026295714.1 (343,)
NW_026295715.1 (220,)
NW_026295716.1 (303,)
NW_026295717.1 (574,)
NW_026295718.1 (235,)
NW_026295719.1 (1390,)
NW_026295720.1 (200,)
NW_026295721.1 (440,)
NW_026295722.1 (324,)
NW_026295723.1 (29952,)
NW_026295724.1 (260,)
NW_026295725.1 (295,)
NW_026295726.1 (217,)
NW_026295727.1 (231,)
NW_026295728.1 (256,)
NW_026295729.1 (202,)
NW_026295730.1 (816,)
NW_026295731.1 (204,)
NW_026295732.1 (374,)
NW_026295733.1 (929,)
NW_026295734.1 (515,)
NW_026295735.1 (203,)
NW_026295736.1 (261,)
NW_026295737.1 (221,)
NW_026295738.1 (202,)
NW_026295739.1 (613,)
NW_026295740.1 (717,)
NW_026295741.1 (275,)
NW_026295742.1 (242,)
NW_026295743.1 (265,)
NW_026295744.1 (522,)
NW_026295745.1 (199,)
NW_026295746.1 (396,)
NW_026295747.1 (287,)

In [7]:
df = pd.DataFrame(
    list(zip(chr_names, starts, ends, scores)),
    columns=["chrom", "start", "end", "score"]
)

In [11]:
out_path = 'GCF_001194135.2_ASM119413v2_zdna_thr025.bedgraph'
# Optional track line (UCSC/IGV will ignore if not needed)
track = 'track type=bedGraph name="ZDNA_thr0.25" description="mean score per segment" visibility=full autoScale=on'
with open(out_path, 'w') as out:
    out.write(track + '\n')
    df[["chrom", "start", "end", "score"]].to_csv(out, sep='\t', header=False, index=False)
print(f"Wrote BedGraph: {out_path}")

Wrote BedGraph: GCF_001194135.2_ASM119413v2_zdna_thr025.bedgraph

In [13]:
from tqdm import trange
model_confidence_threshold = 0.25
min_len = 4

chr_names, starts, ends, scores = [], [], [], []

for fname in os.listdir('predictions_g4/'):
    print(fname)
    with open('predictions_g4/' + fname,'rb') as f:
        preds = pickle.load(f)
        
    if fname.startswith('NW_'):
        for k, arr in preds.items():
            print(k, arr.shape)
            extract_segments_1d(
            arr=arr,
            name=k,
            threshold=model_confidence_threshold,
            min_len=min_len,
            chr_names=chr_names,
            starts=starts,
            ends=ends,
            scores=scores,
        )
    else:
        print(preds.shape)
        extract_segments_1d(
        arr=preds,
        name=fname.replace('.pickle', ''),
        threshold=model_confidence_threshold,
        min_len=min_len,
        chr_names=chr_names,
        starts=starts,
        ends=ends,
        scores=scores,
    )

NC_068981.1.pickle
(199874324,)
NC_068982.1.pickle
(192492725,)
NC_068983.1.pickle
(168056172,)
NC_068984.1.pickle
(147805811,)
NC_068985.1.pickle
(127476054,)
NC_068986.1.pickle
(117080274,)
NC_068987.1.pickle
(110520654,)
NC_068988.1.pickle
(97793168,)
NC_068989.1.pickle
(96881191,)
NC_068990.1.pickle
(94598369,)
NC_068991.1.pickle
(80868366,)
NC_068992.1.pickle
(68459955,)
NC_068993.1.pickle
(65066832,)
NC_068994.1.pickle
(60576129,)
NC_068995.1.pickle
(58155570,)
NC_068996.1.pickle
(57524426,)
NC_068997.1.pickle
(57421545,)
NC_068998.1.pickle
(55557499,)
NC_068999.1.pickle
(55137724,)
NC_069000.1.pickle
(47890966,)
NC_069001.1.pickle
(40062745,)
NC_069002.1.pickle
(37717994,)
NC_069003.1.pickle
(37682606,)
NC_069004.1.pickle
(36166158,)
NC_069005.1.pickle
(35489831,)
NC_069006.1.pickle
(26644802,)
NC_069007.1.pickle
(22553644,)
NC_069008.1.pickle
(18637140,)
NC_069009.1.pickle
(11991808,)
NC_069010.1.pickle
(10083076,)
NC_029723.1.pickle
(15728,)
NW__all.pickle
NW_026294888.1 (344,)
NW_026294889.1 (825,)
NW_026294890.1 (381,)
NW_026294891.1 (387,)
NW_026294892.1 (318,)
NW_026294893.1 (469,)
NW_026294894.1 (338,)
NW_026294895.1 (491,)
NW_026294896.1 (420,)
NW_026294897.1 (354,)
NW_026294898.1 (225,)
NW_026294899.1 (235,)
NW_026294900.1 (312,)
NW_026294901.1 (365,)
NW_026294902.1 (359,)
NW_026294903.1 (422,)
NW_026294904.1 (460,)
NW_026294905.1 (2874,)
NW_026294906.1 (485,)
NW_026294907.1 (633,)
NW_026294908.1 (671,)
NW_026294909.1 (2554,)
NW_026294910.1 (209,)
NW_026294911.1 (214,)
NW_026294912.1 (235,)
NW_026294913.1 (813,)
NW_026294914.1 (488,)
NW_026294915.1 (202,)
NW_026294916.1 (244,)
NW_026294917.1 (519,)
NW_026294918.1 (446,)
NW_026294919.1 (207,)
NW_026294920.1 (393,)
NW_026294921.1 (401,)
NW_026294922.1 (220,)
NW_026294923.1 (453,)
NW_026294924.1 (344,)
NW_026294925.1 (215,)
NW_026294926.1 (451,)
NW_026294927.1 (1736,)
NW_026294928.1 (245,)
NW_026294929.1 (395,)
NW_026294930.1 (339,)
NW_026294931.1 (249,)
NW_026294932.1 (231,)
NW_026294933.1 (211,)
NW_026294934.1 (331,)
NW_026294935.1 (198,)
NW_026294936.1 (483,)
NW_026294937.1 (547,)
NW_026294938.1 (412,)
NW_026294939.1 (494,)
NW_026294940.1 (257,)
NW_026294941.1 (271,)
NW_026294942.1 (254,)
NW_026294943.1 (634,)
NW_026294944.1 (315,)
NW_026294945.1 (390,)
NW_026294946.1 (520,)
NW_026294947.1 (545,)
NW_026294948.1 (297,)
NW_026294949.1 (630,)
NW_026294950.1 (535,)
NW_026294951.1 (495,)
NW_026294952.1 (540,)
NW_026294953.1 (198,)
NW_026294954.1 (244,)
NW_026294955.1 (223,)
NW_026294956.1 (679,)
NW_026294957.1 (267,)
NW_026294958.1 (397,)
NW_026294959.1 (351,)
NW_026294960.1 (355,)
NW_026294961.1 (344,)
NW_026294962.1 (274,)
NW_026294963.1 (356,)
NW_026294964.1 (360,)
NW_026294965.1 (211,)
NW_026294966.1 (298,)
NW_026294967.1 (423,)
NW_026294968.1 (238,)
NW_026294969.1 (362,)
NW_026294970.1 (446,)
NW_026294971.1 (372,)
NW_026294972.1 (258,)
NW_026294973.1 (272,)
NW_026294974.1 (223,)
NW_026294975.1 (364,)
NW_026294976.1 (251,)
NW_026294977.1 (647,)
NW_026294978.1 (420,)
NW_026294979.1 (364,)
NW_026294980.1 (740,)
NW_026294981.1 (199,)
NW_026294982.1 (361,)
NW_026294983.1 (254,)
NW_026294984.1 (507,)
NW_026294985.1 (213,)
NW_026294986.1 (533,)
NW_026294987.1 (333,)
NW_026294988.1 (276,)
NW_026294989.1 (205,)
NW_026294990.1 (197,)
NW_026294991.1 (2002,)
NW_026294992.1 (397,)
NW_026294993.1 (775,)
NW_026294994.1 (370,)
NW_026294995.1 (627,)
NW_026294996.1 (224,)
NW_026294997.1 (470,)
NW_026294998.1 (332,)
NW_026294999.1 (314,)
NW_026295000.1 (340,)
NW_026295001.1 (316,)
NW_026295002.1 (690,)
NW_026295003.1 (265,)
NW_026295004.1 (428,)
NW_026295005.1 (358,)
NW_026295006.1 (435,)
NW_026295007.1 (315,)
NW_026295008.1 (365,)
NW_026295009.1 (540,)
NW_026295010.1 (298,)
NW_026295011.1 (470,)
NW_026295012.1 (410,)
NW_026295013.1 (197,)
NW_026295014.1 (509,)
NW_026295015.1 (352,)
NW_026295016.1 (2151,)
NW_026295017.1 (263,)
NW_026295018.1 (207,)
NW_026295019.1 (2030,)
NW_026295020.1 (507,)
NW_026295021.1 (478,)
NW_026295022.1 (428,)
NW_026295023.1 (469,)
NW_026295024.1 (468,)
NW_026295025.1 (463,)
NW_026295026.1 (366,)
NW_026295027.1 (458,)
NW_026295028.1 (304,)
NW_026295029.1 (210,)
NW_026295030.1 (1318,)
NW_026295031.1 (198,)
NW_026295032.1 (1952,)
NW_026295033.1 (1250,)
NW_026295034.1 (540,)
NW_026295035.1 (288,)
NW_026295036.1 (513,)
NW_026295037.1 (712,)
NW_026295038.1 (297,)
NW_026295039.1 (229,)
NW_026295040.1 (447,)
NW_026295041.1 (225,)
NW_026295042.1 (206,)
NW_026295043.1 (253,)
NW_026295044.1 (363,)
NW_026295045.1 (553,)
NW_026295046.1 (319,)
NW_026295047.1 (647,)
NW_026295048.1 (548,)
NW_026295049.1 (2365,)
NW_026295050.1 (426,)
NW_026295051.1 (430,)
NW_026295052.1 (266,)
NW_026295053.1 (219,)
NW_026295054.1 (610,)
NW_026295055.1 (445,)
NW_026295056.1 (334,)
NW_026295057.1 (279,)
NW_026295058.1 (218,)
NW_026295059.1 (317,)
NW_026295060.1 (12136,)
NW_026295061.1 (308,)
NW_026295062.1 (348,)
NW_026295063.1 (337,)
NW_026295064.1 (203,)
NW_026295065.1 (302,)
NW_026295066.1 (635,)
NW_026295067.1 (382,)
NW_026295068.1 (287,)
NW_026295069.1 (575,)
NW_026295070.1 (510,)
NW_026295071.1 (212,)
NW_026295072.1 (475,)
NW_026295073.1 (399,)
NW_026295074.1 (355,)
NW_026295075.1 (363,)
NW_026295076.1 (235,)
NW_026295077.1 (738,)
NW_026295078.1 (245,)
NW_026295079.1 (2031,)
NW_026295080.1 (271,)
NW_026295081.1 (348,)
NW_026295082.1 (333,)
NW_026295083.1 (564,)
NW_026295084.1 (350,)
NW_026295085.1 (216,)
NW_026295086.1 (202,)
NW_026295087.1 (227,)
NW_026295088.1 (238,)
NW_026295089.1 (226,)
NW_026295090.1 (234,)
NW_026295091.1 (392,)
NW_026295092.1 (666,)
NW_026295093.1 (289,)
NW_026295094.1 (229,)
NW_026295095.1 (198,)
NW_026295096.1 (390,)
NW_026295097.1 (239,)
NW_026295098.1 (238,)
NW_026295099.1 (618,)
NW_026295100.1 (253,)
NW_026295101.1 (227,)
NW_026295102.1 (230,)
NW_026295103.1 (283,)
NW_026295104.1 (212,)
NW_026295105.1 (447,)
NW_026295106.1 (451,)
NW_026295107.1 (409,)
NW_026295108.1 (437,)
NW_026295109.1 (314,)
NW_026295110.1 (288,)
NW_026295111.1 (223,)
NW_026295112.1 (503,)
NW_026295113.1 (266,)
NW_026295114.1 (377,)
NW_026295115.1 (952,)
NW_026295116.1 (261,)
NW_026295117.1 (264,)
NW_026295118.1 (543,)
NW_026295119.1 (751,)
NW_026295120.1 (739,)
NW_026295121.1 (238,)
NW_026295122.1 (217,)
NW_026295123.1 (623,)
NW_026295124.1 (317,)
NW_026295125.1 (495,)
NW_026295126.1 (235,)
NW_026295127.1 (509,)
NW_026295128.1 (196,)
NW_026295129.1 (253,)
NW_026295130.1 (463,)
NW_026295131.1 (414,)
NW_026295132.1 (638,)
NW_026295133.1 (294,)
NW_026295134.1 (222,)
NW_026295135.1 (445,)
NW_026295136.1 (703,)
NW_026295137.1 (447,)
NW_026295138.1 (441,)
NW_026295139.1 (247,)
NW_026295140.1 (279,)
NW_026295141.1 (547,)
NW_026295142.1 (1338,)
NW_026295143.1 (671,)
NW_026295144.1 (2101,)
NW_026295145.1 (470,)
NW_026295146.1 (527,)
NW_026295147.1 (490,)
NW_026295148.1 (672,)
NW_026295149.1 (323,)
NW_026295150.1 (1077,)
NW_026295151.1 (221,)
NW_026295152.1 (2869,)
NW_026295153.1 (239,)
NW_026295154.1 (226,)
NW_026295155.1 (437,)
NW_026295156.1 (246,)
NW_026295157.1 (352,)
NW_026295158.1 (506,)
NW_026295159.1 (566,)
NW_026295160.1 (307,)
NW_026295161.1 (357,)
NW_026295162.1 (203,)
NW_026295163.1 (242,)
NW_026295164.1 (215,)
NW_026295165.1 (211,)
NW_026295166.1 (219,)
NW_026295167.1 (231,)
NW_026295168.1 (794,)
NW_026295169.1 (198,)
NW_026295170.1 (520,)
NW_026295171.1 (374,)
NW_026295172.1 (483,)
NW_026295173.1 (18630,)
NW_026295174.1 (417,)
NW_026295175.1 (421,)
NW_026295176.1 (236,)
NW_026295177.1 (396,)
NW_026295178.1 (542,)
NW_026295179.1 (278,)
NW_026295180.1 (357,)
NW_026295181.1 (483,)
NW_026295182.1 (227,)
NW_026295183.1 (394,)
NW_026295184.1 (330,)
NW_026295185.1 (456,)
NW_026295186.1 (290,)
NW_026295187.1 (201,)
NW_026295188.1 (582,)
NW_026295189.1 (319,)
NW_026295190.1 (1899,)
NW_026295191.1 (266,)
NW_026295192.1 (205,)
NW_026295193.1 (353,)
NW_026295194.1 (319,)
NW_026295195.1 (225,)
NW_026295196.1 (1152,)
NW_026295197.1 (1029,)
NW_026295198.1 (964,)
NW_026295199.1 (459,)
NW_026295200.1 (493,)
NW_026295201.1 (278,)
NW_026295202.1 (322,)
NW_026295203.1 (222,)
NW_026295204.1 (343,)
NW_026295205.1 (343,)
NW_026295206.1 (231,)
NW_026295207.1 (206,)
NW_026295208.1 (629,)
NW_026295209.1 (2085,)
NW_026295210.1 (407,)
NW_026295211.1 (394,)
NW_026295212.1 (219,)
NW_026295213.1 (214,)
NW_026295214.1 (979,)
NW_026295215.1 (299,)
NW_026295216.1 (491,)
NW_026295217.1 (623,)
NW_026295218.1 (14427,)
NW_026295219.1 (487,)
NW_026295220.1 (322,)
NW_026295221.1 (198,)
NW_026295222.1 (534,)
NW_026295223.1 (283,)
NW_026295224.1 (290,)
NW_026295225.1 (445,)
NW_026295226.1 (574,)
NW_026295227.1 (202,)
NW_026295228.1 (467,)
NW_026295229.1 (370,)
NW_026295230.1 (529,)
NW_026295231.1 (359,)
NW_026295232.1 (391,)
NW_026295233.1 (585,)
NW_026295234.1 (350,)
NW_026295235.1 (243,)
NW_026295236.1 (220,)
NW_026295237.1 (963,)
NW_026295238.1 (370,)
NW_026295239.1 (508,)
NW_026295240.1 (266,)
NW_026295241.1 (383,)
NW_026295242.1 (447,)
NW_026295243.1 (518,)
NW_026295244.1 (314,)
NW_026295245.1 (275,)
NW_026295246.1 (322,)
NW_026295247.1 (211,)
NW_026295248.1 (616,)
NW_026295249.1 (350,)
NW_026295250.1 (239,)
NW_026295251.1 (222,)
NW_026295252.1 (308,)
NW_026295253.1 (253,)
NW_026295254.1 (622,)
NW_026295255.1 (268,)
NW_026295256.1 (378,)
NW_026295257.1 (226,)
NW_026295258.1 (660,)
NW_026295259.1 (1817,)
NW_026295260.1 (570,)
NW_026295261.1 (4845,)
NW_026295262.1 (2742,)
NW_026295263.1 (573,)
NW_026295264.1 (537,)
NW_026295265.1 (450,)
NW_026295266.1 (853,)
NW_026295267.1 (216,)
NW_026295268.1 (3440,)
NW_026295269.1 (1588,)
NW_026295270.1 (228,)
NW_026295271.1 (205,)
NW_026295272.1 (357,)
NW_026295273.1 (528,)
NW_026295274.1 (255,)
NW_026295275.1 (229,)
NW_026295276.1 (398,)
NW_026295277.1 (525,)
NW_026295278.1 (368,)
NW_026295279.1 (527,)
NW_026295280.1 (342,)
NW_026295281.1 (323,)
NW_026295282.1 (490,)
NW_026295283.1 (344,)
NW_026295284.1 (493,)
NW_026295285.1 (452,)
NW_026295286.1 (591,)
NW_026295287.1 (471,)
NW_026295288.1 (273,)
NW_026295289.1 (250,)
NW_026295290.1 (288,)
NW_026295291.1 (291,)
NW_026295292.1 (285,)
NW_026295293.1 (2161,)
NW_026295294.1 (619,)
NW_026295295.1 (388,)
NW_026295296.1 (292,)
NW_026295297.1 (621,)
NW_026295298.1 (416,)
NW_026295299.1 (331,)
NW_026295300.1 (298,)
NW_026295301.1 (1356,)
NW_026295302.1 (349,)
NW_026295303.1 (200,)
NW_026295304.1 (1896,)
NW_026295305.1 (297,)
NW_026295306.1 (555,)
NW_026295307.1 (213,)
NW_026295308.1 (221,)
NW_026295309.1 (438,)
NW_026295310.1 (614,)
NW_026295311.1 (740,)
NW_026295312.1 (780,)
NW_026295313.1 (209,)
NW_026295314.1 (478,)
NW_026295315.1 (231,)
NW_026295316.1 (275,)
NW_026295317.1 (215,)
NW_026295318.1 (494,)
NW_026295319.1 (393,)
NW_026295320.1 (465,)
NW_026295321.1 (265,)
NW_026295322.1 (649,)
NW_026295323.1 (389,)
NW_026295324.1 (266,)
NW_026295325.1 (289,)
NW_026295326.1 (4732,)
NW_026295327.1 (342,)
NW_026295328.1 (198,)
NW_026295329.1 (357,)
NW_026295330.1 (500,)
NW_026295331.1 (422,)
NW_026295332.1 (20059,)
NW_026295333.1 (369,)
NW_026295334.1 (1095,)
NW_026295335.1 (256,)
NW_026295336.1 (4750,)
NW_026295337.1 (517,)
NW_026295338.1 (474,)
NW_026295339.1 (198,)
NW_026295340.1 (681,)
NW_026295341.1 (271,)
NW_026295342.1 (372,)
NW_026295343.1 (202,)
NW_026295344.1 (570,)
NW_026295345.1 (1989,)
NW_026295346.1 (658,)
NW_026295347.1 (223,)
NW_026295348.1 (425,)
NW_026295349.1 (429,)
NW_026295350.1 (13614,)
NW_026295351.1 (223,)
NW_026295352.1 (676,)
NW_026295353.1 (374,)
NW_026295354.1 (522,)
NW_026295355.1 (363,)
NW_026295356.1 (649,)
NW_026295357.1 (811,)
NW_026295358.1 (637,)
NW_026295359.1 (615,)
NW_026295360.1 (546,)
NW_026295361.1 (320,)
NW_026295362.1 (541,)
NW_026295363.1 (424,)
NW_026295364.1 (714,)
NW_026295365.1 (549,)
NW_026295366.1 (322,)
NW_026295367.1 (597,)
NW_026295368.1 (429,)
NW_026295369.1 (530,)
NW_026295370.1 (420,)
NW_026295371.1 (378,)
NW_026295372.1 (1140,)
NW_026295373.1 (696,)
NW_026295374.1 (195,)
NW_026295375.1 (362,)
NW_026295376.1 (252,)
NW_026295377.1 (1013,)
NW_026295378.1 (439,)
NW_026295379.1 (279,)
NW_026295380.1 (568,)
NW_026295381.1 (239,)
NW_026295382.1 (464,)
NW_026295383.1 (344,)
NW_026295384.1 (260,)
NW_026295385.1 (3072,)
NW_026295386.1 (255,)
NW_026295387.1 (428,)
NW_026295388.1 (252,)
NW_026295389.1 (1657,)
NW_026295390.1 (354,)
NW_026295391.1 (374,)
NW_026295392.1 (272,)
NW_026295393.1 (348,)
NW_026295394.1 (298,)
NW_026295395.1 (267,)
NW_026295396.1 (602,)
NW_026295397.1 (204,)
NW_026295398.1 (1102,)
NW_026295399.1 (326,)
NW_026295400.1 (341,)
NW_026295401.1 (254,)
NW_026295402.1 (218,)
NW_026295403.1 (258,)
NW_026295404.1 (522,)
NW_026295405.1 (233,)
NW_026295406.1 (547,)
NW_026295407.1 (512,)
NW_026295408.1 (1931,)
NW_026295409.1 (576,)
NW_026295410.1 (1457,)
NW_026295411.1 (379,)
NW_026295412.1 (324,)
NW_026295413.1 (227,)
NW_026295414.1 (577,)
NW_026295415.1 (309,)
NW_026295416.1 (228,)
NW_026295417.1 (354,)
NW_026295418.1 (257,)
NW_026295419.1 (259,)
NW_026295420.1 (342,)
NW_026295421.1 (500,)
NW_026295422.1 (617,)
NW_026295423.1 (535,)
NW_026295424.1 (515,)
NW_026295425.1 (10376,)
NW_026295426.1 (375,)
NW_026295427.1 (1183,)
NW_026295428.1 (468,)
NW_026295429.1 (2024,)
NW_026295430.1 (210,)
NW_026295431.1 (728,)
NW_026295432.1 (365,)
NW_026295433.1 (476,)
NW_026295434.1 (351,)
NW_026295435.1 (2291,)
NW_026295436.1 (4111,)
NW_026295437.1 (1771,)
NW_026295438.1 (1633,)
NW_026295439.1 (196,)
NW_026295440.1 (309,)
NW_026295441.1 (676,)
NW_026295442.1 (438,)
NW_026295443.1 (254,)
NW_026295444.1 (391,)
NW_026295445.1 (525,)
NW_026295446.1 (405,)
NW_026295447.1 (2112,)
NW_026295448.1 (373,)
NW_026295449.1 (583,)
NW_026295450.1 (362,)
NW_026295451.1 (399,)
NW_026295452.1 (316,)
NW_026295453.1 (233,)
NW_026295454.1 (236,)
NW_026295455.1 (244,)
NW_026295456.1 (270,)
NW_026295457.1 (230,)
NW_026295458.1 (243,)
NW_026295459.1 (524,)
NW_026295460.1 (227,)
NW_026295461.1 (203,)
NW_026295462.1 (386,)
NW_026295463.1 (633,)
NW_026295464.1 (204,)
NW_026295465.1 (223,)
NW_026295466.1 (206,)
NW_026295467.1 (234,)
NW_026295468.1 (2012,)
NW_026295469.1 (575,)
NW_026295470.1 (291,)
NW_026295471.1 (298,)
NW_026295472.1 (465,)
NW_026295473.1 (536,)
NW_026295474.1 (247,)
NW_026295475.1 (219,)
NW_026295476.1 (230,)
NW_026295477.1 (397,)
NW_026295478.1 (263,)
NW_026295479.1 (273,)
NW_026295480.1 (1940,)
NW_026295481.1 (199,)
NW_026295482.1 (273,)
NW_026295483.1 (1900,)
NW_026295484.1 (359,)
NW_026295485.1 (304,)
NW_026295486.1 (216,)
NW_026295487.1 (432,)
NW_026295488.1 (365,)
NW_026295489.1 (378,)
NW_026295490.1 (694,)
NW_026295491.1 (339,)
NW_026295492.1 (338,)
NW_026295493.1 (207,)
NW_026295494.1 (204,)
NW_026295495.1 (525,)
NW_026295496.1 (239,)
NW_026295497.1 (315,)
NW_026295498.1 (416,)
NW_026295499.1 (320,)
NW_026295500.1 (258,)
NW_026295501.1 (351,)
NW_026295502.1 (237,)
NW_026295503.1 (480,)
NW_026295504.1 (362,)
NW_026295505.1 (686,)
NW_026295506.1 (556,)
NW_026295507.1 (208,)
NW_026295508.1 (397,)
NW_026295509.1 (593,)
NW_026295510.1 (241,)
NW_026295511.1 (580,)
NW_026295512.1 (4140,)
NW_026295513.1 (223,)
NW_026295514.1 (453,)
NW_026295515.1 (549,)
NW_026295516.1 (237,)
NW_026295517.1 (367,)
NW_026295518.1 (415,)
NW_026295519.1 (294,)
NW_026295520.1 (29748,)
NW_026295521.1 (560,)
NW_026295522.1 (214,)
NW_026295523.1 (301,)
NW_026295524.1 (487,)
NW_026295525.1 (492,)
NW_026295526.1 (217,)
NW_026295527.1 (8299,)
NW_026295528.1 (1176,)
NW_026295529.1 (3603,)
NW_026295530.1 (230,)
NW_026295531.1 (293,)
NW_026295532.1 (465,)
NW_026295533.1 (535,)
NW_026295534.1 (406,)
NW_026295535.1 (204,)
NW_026295536.1 (601,)
NW_026295537.1 (334,)
NW_026295538.1 (756,)
NW_026295539.1 (487,)
NW_026295540.1 (359,)
NW_026295541.1 (213,)
NW_026295542.1 (489,)
NW_026295543.1 (433,)
NW_026295544.1 (313,)
NW_026295545.1 (355,)
NW_026295546.1 (255,)
NW_026295547.1 (355,)
NW_026295548.1 (211,)
NW_026295549.1 (387,)
NW_026295550.1 (4975,)
NW_026295551.1 (471,)
NW_026295552.1 (268,)
NW_026295553.1 (536,)
NW_026295554.1 (393,)
NW_026295555.1 (570,)
NW_026295556.1 (643,)
NW_026295557.1 (8710,)
NW_026295558.1 (577,)
NW_026295559.1 (558,)
NW_026295560.1 (199,)
NW_026295561.1 (1532,)
NW_026295562.1 (433,)
NW_026295563.1 (330,)
NW_026295564.1 (207,)
NW_026295565.1 (362,)
NW_026295566.1 (254,)
NW_026295567.1 (5947,)
NW_026295568.1 (416,)
NW_026295569.1 (242,)
NW_026295570.1 (471,)
NW_026295571.1 (312,)
NW_026295572.1 (573,)
NW_026295573.1 (446,)
NW_026295574.1 (462,)
NW_026295575.1 (538,)
NW_026295576.1 (5129,)
NW_026295577.1 (290,)
NW_026295578.1 (438,)
NW_026295579.1 (478,)
NW_026295580.1 (210,)
NW_026295581.1 (216,)
NW_026295582.1 (236,)
NW_026295583.1 (316,)
NW_026295584.1 (446,)
NW_026295585.1 (602,)
NW_026295586.1 (325,)
NW_026295587.1 (361,)
NW_026295588.1 (589,)
NW_026295589.1 (316,)
NW_026295590.1 (891,)
NW_026295591.1 (231,)
NW_026295592.1 (441,)
NW_026295593.1 (521,)
NW_026295594.1 (759,)
NW_026295595.1 (531,)
NW_026295596.1 (474,)
NW_026295597.1 (213,)
NW_026295598.1 (522,)
NW_026295599.1 (593,)
NW_026295600.1 (552,)
NW_026295601.1 (457,)
NW_026295602.1 (626,)
NW_026295603.1 (737,)
NW_026295604.1 (231,)
NW_026295605.1 (414,)
NW_026295606.1 (241,)
NW_026295607.1 (242,)
NW_026295608.1 (524,)
NW_026295609.1 (199,)
NW_026295610.1 (208,)
NW_026295611.1 (295,)
NW_026295612.1 (473,)
NW_026295613.1 (284,)
NW_026295614.1 (427,)
NW_026295615.1 (287,)
NW_026295616.1 (308,)
NW_026295617.1 (422,)
NW_026295618.1 (211,)
NW_026295619.1 (266,)
NW_026295620.1 (224,)
NW_026295621.1 (604,)
NW_026295622.1 (490,)
NW_026295623.1 (312,)
NW_026295624.1 (4145,)
NW_026295625.1 (265,)
NW_026295626.1 (387,)
NW_026295627.1 (1886,)
NW_026295628.1 (502,)
NW_026295629.1 (457,)
NW_026295630.1 (218,)
NW_026295631.1 (232,)
NW_026295632.1 (1578,)
NW_026295633.1 (1965,)
NW_026295634.1 (4956,)
NW_026295635.1 (395,)
NW_026295636.1 (273,)
NW_026295637.1 (240,)
NW_026295638.1 (297,)
NW_026295639.1 (218,)
NW_026295640.1 (197,)
NW_026295641.1 (245,)
NW_026295642.1 (344,)
NW_026295643.1 (316,)
NW_026295644.1 (309,)
NW_026295645.1 (276,)
NW_026295646.1 (658,)
NW_026295647.1 (853,)
NW_026295648.1 (228,)
NW_026295649.1 (333,)
NW_026295650.1 (369,)
NW_026295651.1 (207,)
NW_026295652.1 (281,)
NW_026295653.1 (345,)
NW_026295654.1 (334,)
NW_026295655.1 (692,)
NW_026295656.1 (405,)
NW_026295657.1 (385,)
NW_026295658.1 (270,)
NW_026295659.1 (206,)
NW_026295660.1 (236,)
NW_026295661.1 (353,)
NW_026295662.1 (504,)
NW_026295663.1 (287,)
NW_026295664.1 (207,)
NW_026295665.1 (408,)
NW_026295666.1 (509,)
NW_026295667.1 (289,)
NW_026295668.1 (553,)
NW_026295669.1 (758,)
NW_026295670.1 (1451,)
NW_026295671.1 (261,)
NW_026295672.1 (604,)
NW_026295673.1 (1100,)
NW_026295674.1 (220,)
NW_026295675.1 (653,)
NW_026295676.1 (450,)
NW_026295677.1 (373,)
NW_026295678.1 (325,)
NW_026295679.1 (205,)
NW_026295680.1 (234,)
NW_026295681.1 (623,)
NW_026295682.1 (242,)
NW_026295683.1 (366,)
NW_026295684.1 (577,)
NW_026295685.1 (268,)
NW_026295686.1 (242,)
NW_026295687.1 (238,)
NW_026295688.1 (268,)
NW_026295689.1 (200,)
NW_026295690.1 (2061,)
NW_026295691.1 (3820,)
NW_026295692.1 (247,)
NW_026295693.1 (558,)
NW_026295694.1 (912,)
NW_026295695.1 (562,)
NW_026295696.1 (428,)
NW_026295697.1 (223,)
NW_026295698.1 (349,)
NW_026295699.1 (577,)
NW_026295700.1 (264,)
NW_026295701.1 (248,)
NW_026295702.1 (210,)
NW_026295703.1 (246,)
NW_026295704.1 (315,)
NW_026295705.1 (214,)
NW_026295706.1 (385,)
NW_026295707.1 (347,)
NW_026295708.1 (329,)
NW_026295709.1 (18688,)
NW_026295710.1 (203,)
NW_026295711.1 (369,)
NW_026295712.1 (249,)
NW_026295713.1 (252,)
NW_026295714.1 (343,)
NW_026295715.1 (220,)
NW_026295716.1 (303,)
NW_026295717.1 (574,)
NW_026295718.1 (235,)
NW_026295719.1 (1390,)
NW_026295720.1 (200,)
NW_026295721.1 (440,)
NW_026295722.1 (324,)
NW_026295723.1 (29952,)
NW_026295724.1 (260,)
NW_026295725.1 (295,)
NW_026295726.1 (217,)
NW_026295727.1 (231,)
NW_026295728.1 (256,)
NW_026295729.1 (202,)
NW_026295730.1 (816,)
NW_026295731.1 (204,)
NW_026295732.1 (374,)
NW_026295733.1 (929,)
NW_026295734.1 (515,)
NW_026295735.1 (203,)
NW_026295736.1 (261,)
NW_026295737.1 (221,)
NW_026295738.1 (202,)
NW_026295739.1 (613,)
NW_026295740.1 (717,)
NW_026295741.1 (275,)
NW_026295742.1 (242,)
NW_026295743.1 (265,)
NW_026295744.1 (522,)
NW_026295745.1 (199,)
NW_026295746.1 (396,)
NW_026295747.1 (287,)

In [15]:
df = pd.DataFrame(
    list(zip(chr_names, starts, ends, scores)),
    columns=["chrom", "start", "end", "score"]
)

In [16]:
out_path = 'GCF_001194135.2_ASM119413v2_G4_thr025.bedgraph'
# Optional track line (UCSC/IGV will ignore if not needed)
track = 'track type=bedGraph name="G4_thr0.25" description="mean score per segment" visibility=full autoScale=on'
with open(out_path, 'w') as out:
    out.write(track + '\n')
    df[["chrom", "start", "end", "score"]].to_csv(out, sep='\t', header=False, index=False)
print(f"Wrote BedGraph: {out_path}")

Wrote BedGraph: GCF_001194135.2_ASM119413v2_G4_thr025.bedgraph

In [17]:
df

                chrom   start     end     score
0         NC_068981.1   96210   96224  0.786792
1         NC_068981.1  139872  139885  0.426565
2         NC_068981.1  140203  140222  0.516117
3         NC_068981.1  291548  291556  0.280562
4         NC_068981.1  382075  382093  0.699734
...               ...     ...     ...       ...
38527  NW_026439921.1    1984    1998  0.365590
38528  NW_026439958.1       0       9  0.280401
38529  NW_026440011.1     195     201  0.467667
38530  NW_026440030.1     103     130  0.559187
38531  NW_026440109.1    3916    3931  0.352104

[38532 rows x 4 columns]

In [29]:
print(len(starts))
print(len(ends))
print(len(chr_names))

264865
264865
264865

In [32]:
df = pd.DataFrame(list(zip(chr_names, starts, ends)))

In [47]:
#[t for t in list(set(df[0].tolist())) if 'Eber_ch' in t]

In [ ]:
#Eber_sc12555

In [44]:
df.sort_values([0])

                  0          1          2
100630     Eber_ch1      19923      19928
105887     Eber_ch1  112364985  112364990
105886     Eber_ch1  112293044  112293060
105885     Eber_ch1  112086886  112086899
105884     Eber_ch1  112086743  112086760
...             ...        ...        ...
188656  Eber_sc9996      17388      17396
188658  Eber_sc9996      23287      23300
188660  Eber_sc9998       3569       3578
188659  Eber_sc9998       3482       3502
188661  Eber_sc9999       3904       3920

[264865 rows x 3 columns]

In [46]:
df.sort_values([0]).to_fwf(f'Eber_ch1-48_sc1-1255_thr05_hg.bed')